CREATE SCHEMA IF NOT EXISTS bd_usuarios;

CREATE TABLE IF NOT EXISTS bd_usuarios.usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(100) NOT NULL,
    rut_usuario VARCHAR(20) NOT NULL,
    contacto_usuario VARCHAR(20) NOT NULL,
    correo_usuario VARCHAR(20) NOT NULL,
    direccion_usuario VARCHAR(20) NOT NULL,
    fecha_usuario DATE NOT NULL
);